### ISSUE TITLE
Decryption failed

### ISSUE THREAD

**Issue by typ431127** [Luzifer/sii#4]
Hello, is this project still under maintenance? I tried to decrypt the game.sii file, but all failed~
>go run main.go game2.sii 1.txt
time="2021-08-02T10:01:35+08:00" level=info msg="Loading input file"
time="2021-08-02T10:01:35+08:00" level=fatal msg="Unit-file parsing failed: Unable to decrypt file"
exit status 1

**Comment by Luzifer** [comment]
No, it isn't really maintained. I've played no ETS/ATS for a long time and haven't updated the project to a recent version (in case there was a change in the file format)…
